# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BitBox
description: Shift Cryptocurrency product user guides
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guides.shiftcrypto.ch" # the base hostname & protocol for your site, e.g. http://example.com
support: "(mailto:support@shiftcrypto.ch)"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

logo: "/assets/favicons/favicon-128.svg"

# Enable or disable the site search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Back to shiftcrypto.ch": "https://shiftcrypto.ch"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2017-2019 Shift Cryptosecurity."

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking:

plugins:
  - jekyll-seo-tag
  - jekyll-get-json

jekyll_get_json:
  - data: guide
    json: 'https://raw.githubusercontent.com/digitalbitbox/bitbox-wallet-app/47fedb10e7816220ff0c33e4f0d1c70932b1a37f/frontends/web/src/locales/en/app.json'

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false

defaults:
  - scope:
      path: "assets/imgages"
    values:
      image: true
